# This file defines all document styling and formatting options

# Document defaults - controls margins and page size
document_defaults:
  margin_top: 0.5  # in inches
  margin_bottom: 1.0  # in inches
  margin_left: 0.5  # in inches
  margin_right: 0.5  # in inches
  page_width: 8.5  # in inches (US Letter)
  page_height: 11.0  # in inches (US Letter)
  # Page number settings
  page_numbers_enabled: false
  page_numbers_alignment: "center"  # left, center, right
  page_numbers_format: "with_total"     # simple, with_total
  page_numbers_text: "Page {page} of {total}"
  # Column settings
  two_column_enabled: false  # Enable the two-column layout
  sidebar_width_ratio: 0.33  # Width ratio of left sidebar (1/3)
  main_width_ratio: 0.67  # Width ratio of main content (2/3)
  sidebar_position: "left"  # Position of sidebar: "left" or "right"

  header_image:
    enabled: false
    url: "https://example.com/your-profile-image.jpg"  # Replace with your actual image URL
    width_inches: 0.8  # Width of the image in inches
    height_inches: 0.8  # Height of the image in inches (make equal to width for square)
    border_color: "BCDCFF"  # Dark blue border color
    border_width: 3  # Border width in points
    double_border: true  # Enable double border effect using nested table
    inner_border_color: "4F81BD"  # Color of the inner border
    inner_border_width: 2  # Width of the inner border in points
    border_spacing: 2  # Space between borders in points
    position: "left"  # Position of the image (left or right)
    margin_right: 0.5  # Margin between image and text in inches
    padding_top: 7      # Padding above the image in points
    padding_right: 18    # Padding to the right of the image in points
    padding_bottom: 7   # Padding below the image in points
    padding_left: 0     # Padding to the left of the image in points
    vertical_alignment: "center"  # Vertical alignment of the image in the cell
  header_alignment: "center"  # Alignment for header text (left, center, or right)
  vertical_alignment: "center"

# Style constants - general formatting preferences
style_constants:
  font_size_pts: 11
  space_before: 10
  space_after: 0
  indent_inches: 0.25
  bullet_indent_inches: 0.5
  hr_before_job_blank_line: true  # Enable/disable blank line before job entries with HR
  horizontal_line_char: "_"  # Character for horizontal lines
  horizontal_line_length: 50  # Length of horizontal line
  horizontal_line_color: "4F81BD"  # Color of horizontal lines
  horizontal_line_spacing: 1.6  # Height of horizontal line
  header_to_about_spacing: 0.8    # Add explicit control for space between header and about
  horizontal_line_font_size: 16
  sidebar_horizontal_line_length: 15  # Length of horizontal line
  sidebar_horizontal_line_color: "4F81BD"  # Color of horizontal lines in sidebar
  sidebar_horizontal_line_font_size: 16
  job_entry_horizontal_line_length: 30  # Length of horizontal line for job entries
  job_entry_horizontal_line_spacing: 1.0  # Height of horizontal line for job
  header_specialty_space_after: 4  # Space after headings
  top_skills_separator_markdown: " • "  # Separator for top skills area
  top_skills_separator: " | "  # Separator for top skills area
  top_skills_bold: true  # Enable/disable bold formatting for top skills
  key_skills_separator_markdown: " · "  # Separator for key skills area
  key_skills_separator: ", "  # Separator for key skills area
  key_skills_bold: true  # Enable/disable bold formatting for key skills
  key_skills_line_spacing: 1.25  # Line spacing for key skills line
  key_skills_font_size: 10  # Font size for key skills line
  key_skills_heading_line_spacing: 1.0  # Line spacing for key skills heading
  date_location_line_spacing: 1.2  # Line spacing for date/location line
  date_location_font_size: 10  # Font size for date/location line
  date_location_separator: " / "  # Separator between date and location
  position_title_line_spacing: 1.0  # Line spacing for position title line
  paragraph_lists: yes  # Enable/disable paragraph-style lists
  page_number_font_size: 8
  page_number_font_name: "Helvetica Neue"

  # Cell margin settings (in twips - 1/20th of a point)
  cell_margin_top: 60      # Top internal margin for table cells
  cell_margin_bottom: 60   # Bottom internal margin for table cells
  cell_margin_left: 200     # Left internal margin for table cells
  cell_margin_right: 200    # Right internal margin for table cells
  # Optional specific margins for different cell types
  about_cell_margin_top: 0    # Custom margin for about section
  sidebar_cell_margin_left: 200  # Custom left margin for sidebar
  main_cell_margin_left: 200    # Custom left margin for main content
  contact_cell_margin_top: 200  # Custom top margin for contact ribbon

  contact_ribbon:
    border_enabled: true  # Enable border for contact ribbon
    border_top_enabled: true  # Enable/disable top border for contact ribbon
    border_bottom_enabled: true  # Enable/disable bottom border for about ribbon
    border_left_enabled: false  # Enable/disable left border for about ribbon
    border_right_enabled: false  # Enable/disable right border for about ribbon
    border_width: 5  # Width of sidebar border in points
    border_top_width: 5
    border_bottom_width: 5
    border_left_width: 1
    border_right_width: 1
    border_color: "FFFFFF"  # White border color
    border_top_color: "FFFFFF"
    border_bottom_color: "FFFFFF"
    border_left_color: "FFFFFF"
    border_right_color: "FFFFFF"
    fill_enabled: true
    fill_color: "BCDCFF"  # Light blue fill color for contact ribbon

  sidebar:
    border_enabled: true  # Enable border for sidebar
    border_top_enabled: true  # Enable/disable top border for sidebar
    border_bottom_enabled: true  # Enable/disable bottom border for sidebar
    border_left_enabled: false  # Enable/disable left border for sidebar
    border_right_enabled: true  # Enable/disable right border for sidebar
    border_width: 5  # Width of sidebar border in points
    border_top_width: 5
    border_bottom_width: 5
    border_left_width: 1
    border_right_width: 5
    border_color: "FFFFFF"
    border_top_color: "FFFFFF"
    border_bottom_color: "FFFFFF"
    border_left_color: "FFFFFF"
    border_right_color: "FFFFFF"
    fill_enabled: true
    fill_color: "EEEEEE"  # Light gray fill color for sidebar

  main_content:
    border_enabled: false  # Enable border for main content
    # border_top_enabled: false  # Enable/disable top border for sidebar
    # border_bottom_enabled: false  # Enable/disable bottom border for sidebar
    # border_left_enabled: false  # Enable/disable left border for sidebar
    # border_right_enabled: false  # Enable/disable right border for sidebar
    border_width: 0  # Width of sidebar border in points
    # border_top_width: 0
    # border_bottom_width: 0
    # border_left_width: 0
    # border_right_width: 0
    border_color: "FFFFFF"
    # border_top_color: "FFFFFF"
    # border_bottom_color: "FFFFFF"
    # border_left_color: "FFFFFF"
    # border_right_color: "FFFFFF"
    fill_enabled: true
    fill_color: "FFFFFF"  # White fill color for main content

  about:
    border_enabled: true  # Enable border for about section
    border_top_enabled: false  # Enable/disable top border for about section
    border_bottom_enabled: true  # Enable/disable bottom border for about section
    border_left_enabled: false  # Enable/disable left border for about section
    border_right_enabled: false  # Enable/disable right border for about section
    border_width: 5  # Width of about border in points
    border_top_width: 5
    border_bottom_width: 5
    border_left_width: 1
    border_right_width: 1
    border_color: "FFFFFF"  # White border color
    border_top_color: "FFFFFF"
    border_bottom_color: "FFFFFF"  # White border color
    border_left_color: "FFFFFF"
    border_right_color: "FFFFFF"
    fill_enabled: true
    fill_color: "CCCCCC"  # Light gray fill color for sidebar

# Document styles - Word document style definitions
document_styles:
  Normal:
    font_name: "Helvetica Neue"
    font_size: 11
    line_spacing: 1.15
    # space_after: 6
    # indent_left: 0.25
    # indent_right: 0.25

  Title:  # Used for your name at the top
    font_name: "Helvetica Neue"
    font_size: 26
    # alignment: CENTER (1)
    color: "17365D"

  Subtitle:  # Used for tagline under name
    font_name: "Times New Roman"
    font_size: 12
    # italic: true
    # alignment: CENTER (1)
    color: "17365D"

  Heading 1:  # H1 - Main section headings
    # font_name: "Helvetica Neue"
    font_size: 16
    # bold: true
    # underline: true
    color: "365F91"
    space_before: 18
    space_after: 4

  Heading 2:  # H2 - Company names
    # font_name: "Helvetica Neue"
    font_size: 14
    # bold: true
    # italic: false
    color: "4F81BD"
    space_before: 8
    line_spacing: 1.0

  Heading 3:  # H3 - Role titles
    # font_name: "Helvetica Neue"
    font_size: 13
    line_spacing: 1.25
    # bold: true
    # italic: false
    color: "4F81BD"
    space_before: 8

  Heading 4:  # H4 - Subsections
    # font_name: "Helvetica Neue"
    font_size: 12
    # bold: true
    # italic: true
    color: "4F81BD"
    space_before: 8

  Heading 5:  # H5 - Responsibilities, Details
    # font_name: "Helvetica Neue"
    font_size: 12
    # bold: true
    # italic: false
    color: "243F60"

  Hyperlink:
    # font_name: "Helvetica Neue"
    # font_size: 11
    underline: true
    color: "038cfc"

  # List Bullet:
    # font_name: "Helvetica Neue"
    # font_size: 11
    # indent_left: 0.5
    # indent_right: 0.5

paragraph_lists:
  ul:
    bullet_character: "•"  # Custom bullet character to use in lists (●, •, ◦, ·, etc.)
    paragraph_delimiter: "\n"  # Line delimiter for paragraph-style lists

paragraph_headings:
  h1:
    level: 0
    paragraph_heading_size: 24
  h2:
    level: 1
    paragraph_heading_size: 16
  h3:
    level: 2
    paragraph_heading_size: 14
  h4:
    level: 3
    paragraph_heading_size: 12
  h5:
    level: 4
    paragraph_heading_size: 11
  h6:
    level: 5
    paragraph_heading_size: 10

resume_sections:
  about:
    markdown_heading: "About"
    docx_heading: "PROFESSIONAL SUMMARY"
    add_space_before_h2: false
    space_after_h2: 14
    add_space_before_h3: true
    space_before_h3: 16
    space_after_h3: 4
  skills:
    markdown_heading: "Top Skills"
    docx_heading: "TOP SKILLS"
    add_space_before_h2: false
    add_space_before_h3: false
  experience:
    markdown_heading: "Experience"
    docx_heading: "WORK EXPERIENCE"
    add_space_before_h2: false
    space_after_h2: 14
    add_space_before_h3: true
    space_before_h3: 24
    space_after_h3: 0
    add_space_before_h4: true
    space_before_h4: 8
    space_after_h4: 0
  projects:
    markdown_heading: "Projects"
    docx_heading: "PROJECTS"
    add_space_before_h2: false
    add_space_before_h3: true
    space_before_h3: 16
    space_after_h3: 2
    space_after_h4: 2
  certifications:
    markdown_heading: "Licenses & certifications"
    docx_heading: "CERTIFICATIONS"
    add_space_before_h2: false
    add_space_before_h3: true
    add_space_before_h4: true
    space_before_h3: 16
    space_before_h4: 4
  education:
    markdown_heading: "Education"
    docx_heading: "EDUCATION"
    add_space_before_h2: false
    add_space_before_h3: false
  contact:
    markdown_heading: "Contact"
    docx_heading: "CONTACT INFORMATION"
    add_space_before_h2: false
    add_space_before_h3: false
